version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: annonce-db-server
      working_dir: /app
      volumes:
        - .:/app
      environment:
        - MYSQL_ROOT_PASSWORD=papamoris
        - MYSQL_DATABASE=annonce_db
        - MYSQL_USER=annonce_db_user
        #- MYSQL_PASSWORD=dbpw
      ports:
        - "3309:3306"

    annonce-webserver:
      image: nginx:alpine
      container_name: annonce-webserver
      working_dir: /app
      volumes:
          - .:/app
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: annonce-php-fpm
      working_dir: /app
      volumes:
        - .:/app
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini